### ISSUE TITLE
登录失败，获取bdstoken失败

### ISSUE THREAD

**Issue by dej00** [PanDownloadServer/Server#10]
登录失败，获取bdstoken失败

**Comment by 954187350** [comment]
+1

**Comment by chengzhida** [comment]
+1

**Comment by lubenweiPD** [comment]
任务管理器观察aria2c.exe进程是否存在

**Comment by dej00** [comment]
存在aria2c.exe进程，且关闭后手动启动，问题依旧

**Comment by yang9814** [comment]
+1

**Comment by yang9814** [comment]
已更新到3.4版本，使用cookie登录，报错：账号登陆失败，获取bdstoken失败

**Comment by lubenweiPD** [comment]
> 已更新到3.4版本，使用cookie登录，报错：账号登陆失败，获取bdstoken失败

cookie不允许有换行符，下个版本分析原因，正确格式：BDUSS=;STOKEN=;

**Comment by tobebetter-123** [comment]
这个问题现在解决不了吗？

**Comment by lzlclzyx** [comment]
我也是。
3.4版本，扫码，账号，cookie登陆都是获取bdstoken失败

**Comment by cxvae** [comment]
我也是遇到这个问题，3.4版本，扫码，账号，cookie登陆都是获取bdstoken失败，如下图：
![7`PQ61YU(PM(8VNH@TYXRNL](https://user-images.githubusercontent.com/70899502/92391134-b2ef6d00-f14e-11ea-8995-0ee21e5ed56e.png)

**Comment by ling52** [comment]
> 我也是遇到这个问题，3.4版本，扫码，账号，cookie登陆都是获取bdstoken失败，如下图：
> ![7`PQ61YU(PM(8VNH@TYXRNL](https://user-images.githubusercontent.com/70899502/92391134-b2ef6d00-f14e-11ea-8995-0ee21e5ed56e.png)

+1

**Comment by bloomchou** [comment]
删了 重新下载 在登陆

**Comment by Forest-Cxh** [comment]
这个问题怎么解决？账号登录失败，获取bdstoken失败？？？

**Comment by Forest-Cxh** [comment]
请问有大佬解决问题了吗？求指导怎么办

**Comment by mynameisyangzy** [comment]
管理员运行

**Comment by fyeason** [comment]
> 管理员运行

管理员运行后并没有解决问题

**Comment by lubenweiPD** [comment]
很奇怪，删了重新下载，然后登陆，或者多试几次，下个版本康康什么情况。。

**Comment by l635u** [comment]
+1

**Comment by BarrySong97** [comment]
已解决
1. windows自带防火墙允许脚本运行 电脑没有其他杀毒软件
2. 不行就多重启几次
3. 我是用的二维码登录，没有任何问题
4. 我直接就用了管理员运行，所以没有管理员运行不知道行不行

**Comment by BarrySong97** [comment]
> 已解决
> 
> 1. windows自带防火墙允许脚本运行 电脑没有其他杀毒软件
> 2. 不行就多重启几次
> 3. 我是用的二维码登录，没有任何问题
> 4. 我直接就用了管理员运行，所以没有管理员运行不知道行不行

aria2c.exe会弹出来询问是否能接入网络，这个应该是关键吧。

**Comment by tommycai8** [comment]
怀疑RedirectHook.dll被windows denfender拦截，报告为Trojan:Win32/Wacatac.D3!ml

**Comment by lubenweiPD** [comment]
根据https://github.com/PanDownloadServer/Server/issues/10#issuecomment-689341462的来看，应该是被杀软拦截了，下个版本试着bypass。
