### ISSUE TITLE
怎么下载安装呢啊

### ISSUE THREAD

**Issue by ZHANG-hengzhi** [PanDownloadServer/Server#107]
大神们，应该怎么安装啊

**Comment by Miroier** [comment]
下载解压就行了，运行exe

**Comment by ZHANG-hengzhi** [comment]
好的，感谢大神




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Miroier"<notifications@github.com&gt;; 
发送时间: 2020年9月17日(星期四) 下午4:10
收件人: "PanDownloadServer/Server"<Server@noreply.github.com&gt;; 
抄送: "张恒志"<594300065@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [PanDownloadServer/Server] 怎么下载安装呢啊 (#107)





 
下载解压就行了，运行exe

**Comment by 1710537013** [comment]
解压时有密码，怎么搞啊，大神

**Comment by yansheng836** [comment]
https://github.com/PanDownloadServer/Server/issues/93
