### ISSUE TITLE
啥玩意啊，咋回事啊，那咋整啊，大佬帮帮忙啊

### ISSUE THREAD

**Issue by zcp208504756** [PanDownloadServer/Server#109]
萌新四连，有点难顶，更新完3.5依旧是获取bdstoken失败

**Comment by xulizheng66** [comment]
获取bdstoken失败

**Comment by lubenweiPD** [comment]
试试新版的3.5.1。

**Comment by xulizheng66** [comment]
3.5.1还是不行，扫码、账号登录、cookie登录都会显示 “获取bdstoken失败”，不登录下载也会报错。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "lubenweiPD"<notifications@github.com&gt;; 
发送时间: 2020年9月20日(星期天) 中午11:32
收件人: "PanDownloadServer/Server"<Server@noreply.github.com&gt;; 
抄送: "徐立峥"<122750351@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [PanDownloadServer/Server] 啥玩意啊，咋回事啊，那咋整啊，大佬帮帮忙啊 (#109)





 
试试新版的3.5.1。
