### ISSUE TITLE
请更新Aria2，

### ISSUE THREAD

**Issue by TongJiaqi0123** [PanDownloadServer/Server#11]
去哪里更新 啊  没找到啊

**Comment by Andrew201801** [comment]
https://kurukurumi.tk/

![image](https://user-images.githubusercontent.com/35620837/91792486-2c1b2b80-ec48-11ea-86b3-4de1cd920c16.png)

**Comment by lubenweiPD** [comment]
楼上的地址可以更新，https://kurukurumi.tk/

**Comment by bin70** [comment]
> 楼上的地址可以更新，https://kurukurumi.tk/

请问解压密码是多少呢
