### ISSUE TITLE
最新3.5.1仍然无法获取bdstoken

### ISSUE THREAD

**Issue by yiquan24** [PanDownloadServer/Server#111]
![HUBA`}4AVQ2`D$K$_}02VXX](https://user-images.githubusercontent.com/25959511/93693700-deeaf500-fb35-11ea-8d47-d08a1cbde9be.png)

**Comment by one-byte-jiang** [comment]
同样如此

**Comment by KZ-c** [comment]
一样,直接登录或者cookie都是获取bdstoken失败

**Comment by eden214** [comment]
+1

**Comment by jqyisbest** [comment]
我可以用欸。

**Comment by zhumaolin** [comment]
+1

**Comment by nwyxcnsyty** [comment]
第一次打开可以登录，第五个账号时失效，之后退出后再次打开，全部失效

**Comment by young1023x2** [comment]
+1 无论怎样登录都是获取bdstoken失败

**Comment by zhumaolin** [comment]
![image](https://user-images.githubusercontent.com/64005424/93695655-9e947280-fb47-11ea-8f78-ba74635118f3.png)

**Comment by ffop963** [comment]
+1

**Comment by xulizheng66** [comment]
+1

**Comment by xyz3201** [comment]
我也同样的情况，好像这种是部分账号/网络条件才会在其他方式都能正常获取BDSTOKEN时仍旧获取不到。
我在PD原版末期时也出现过，但是周围其他人都没这个情况。当时是用了一个代理方式绕过的。

**Comment by rayenzo** [comment]
+1

**Comment by wodecs** [comment]
+1。开代理也不行

**Comment by Sustary** [comment]
同样是bdstoken无法获取，

**Comment by xhyym** [comment]
还是获取不了，没办法登录的

**Comment by CyzzZ911** [comment]
+1，直接登录和用cookie都是获取bdstoken失败

**Comment by lubenweiPD** [comment]
已修复，中文名相关问题。

**Comment by oeoa** [comment]
@lubenweiPD 3.5.2 依然这样
