### ISSUE TITLE
初始化下载引擎失败，即使是通过管理员运行

### ISSUE THREAD

**Issue by nuodunjjj** [PanDownloadServer/Server#113]

**Comment by siwei-li** [comment]
Same issue here

**Comment by lubenweiPD** [comment]
管理员运行，安装VC2017运行库，关闭杀软或者添加到信任。

**Comment by sohaoo** [comment]
火绒要关了就ok了，要么一直报这个错，而且没有火绒没有任何病毒报错，谢谢楼上提醒

**Comment by jackview** [comment]
VC2017安装了，安全卫士也退出了，PanDownload也是以管理员身份运行的，但还是提示初始化下载引擎失败
