### ISSUE TITLE
NB、漂亮

### ISSUE THREAD

**Issue by just805** [PanDownloadServer/Server#121]
![nb](https://user-images.githubusercontent.com/18697510/93729247-3781c700-fbf6-11ea-97d0-42fdae3984e8.png)

NB、漂亮

**Comment by ZhLinYi** [comment]
air2c，你在哪里更新的呢？B站推得GitHub的文件好像delete了，能问下么?

**Comment by ZhLinYi** [comment]
> 
> 
> ![nb](https://user-images.githubusercontent.com/18697510/93729247-3781c700-fbf6-11ea-97d0-42fdae3984e8.png)
> 
> NB、漂亮

air2c，你在哪里更新的呢？B站推得GitHub的文件好像delete了，能问下么?

**Comment by just805** [comment]
> > ![b](https://user-images.githubusercontent.com/18697510/93729247-3781c700-fbf6-11ea-97d0-42fdae3984e8.png)
> > NB，漂亮
> 
> air2c，你在哪里更新的呢？B站推得GitHub的文件好像删除了，能问下么？

可以访问官网；http://aria2.github.io/
