### ISSUE TITLE
登录报错

### ISSUE THREAD

**Issue by yutons** [PanDownloadServer/Server#122]
![image](https://user-images.githubusercontent.com/25010191/93745713-90695380-fc26-11ea-866e-b6e40b99d8bf.png)

**Comment by lubenweiPD** [comment]
扫码和cookie登陆试试，cookie不允许有换行符，然后再次进行测试。

**Comment by IronmanJay** [comment]
扫码也不可以啊兄弟

**Comment by lubenweiPD** [comment]
如果还是不能登陆，可以把cookie发我试试，或者尝试更改百度云盘用户名为纯英文。

**Comment by Kaworublue** [comment]
初始化失败？

**Comment by lubenweiPD** [comment]
已更新新版，请尝试。
