### ISSUE TITLE
获取bdstoken失败

### ISSUE THREAD

**Issue by coderfruit** [PanDownloadServer/Server#123]
![image](https://user-images.githubusercontent.com/32920880/93748094-42eee580-fc2a-11ea-9c57-d96b7935f57d.png)

**Comment by FangJun2016** [comment]
扫码,cookie登录都获取bdstoken失败

**Comment by TheYon** [comment]
@coderfruit 你好！

请问你是用什么方式进行登录的

我的是可以用，
版本号 3.5.2
登录方式：直接下载node.dll 使用时将node.dll放到pandownload.exe同目录 ( webkit核心，node.dll使用PCS通道下载 )

希望能帮助到你

**Comment by lubenweiPD** [comment]
扫码与cookie均失败吗？cookie不能带换行符，如果还是失败，考虑把cookie私发我。

**Comment by coderfruit** [comment]
> 扫码与cookie均失败吗？cookie不能带换行符，如果还是失败，考虑把cookie私发我。

不好意思，版本弄错了，最新版本没问题了
