### ISSUE TITLE
伞兵五号通道还是提示未登录网盘

### ISSUE THREAD

**Issue by jsxyhyj** [PanDownloadServer/Server#124]
伞兵五号通道蜜写"云解析，无需登陆"，但没有登录时，还是提示未登录网盘

**Comment by lubenweiPD** [comment]
下载什么文件的时候提示的？如果可以，希望把分享链接发出来，分析情况。

**Comment by jsxyhyj** [comment]
你好，链接: https://pan.baidu.com/s/1IvshNy6mxGt9ZWA4SPF2vg 提取码: ehpr       
“【初级基础】：01-零基础学好C#语法与编程逻辑” 里的 “本课程学习资料.zip”，我只添加了这一个任务，开始任务时就报错，未登录。

**Comment by lubenweiPD** [comment]
您可以尝试保存文件到网盘，确保路径中没有特殊字符，然后重试，该问题为编码转换时的错误。下个版本修复，预计国庆节前更新。

**Comment by lubenweiPD** [comment]
已修复。

**Comment by jsxyhyj** [comment]
感谢
