### ISSUE TITLE
登录失败

### ISSUE THREAD

**Issue by Violet616** [PanDownloadServer/Server#125]
![4N~{ L{N H1O 3874}G( ~B](https://user-images.githubusercontent.com/46031145/93773364-a0972800-fc52-11ea-9a1f-77e4ce826d07.png)

**Comment by lubenweiPD** [comment]
再次尝试，看看是否是防火墙拦截了访问。

**Comment by dis-xcl** [comment]
> 再次尝试，看看是否是防火墙拦截了访问。

防火墙、杀软都关了，还是这个错误

**Comment by dl1984** [comment]
![I9`__PM8${ PVGBO~LSBG9H](https://user-images.githubusercontent.com/71760881/93996254-9f860800-fdc4-11ea-8600-d62ea62fec5d.png)
这个怎么搞呢
