### ISSUE TITLE
初始化下载引擎失败9月22号

### ISSUE THREAD

**Issue by soyohoo** [PanDownloadServer/Server#126]
初始化下载引擎失败
![image](https://user-images.githubusercontent.com/53852051/93841437-2b653a80-fcc6-11ea-9bd0-cfb74986c122.png)

**Comment by zs18347474789** [comment]
朋友解压密码是多少

**Comment by pcdd21** [comment]
百度是不是整天盯着我们不让我们好过啊，刚好没几天，就又不能玩了，太缺德了

**Comment by dxyhymn** [comment]
同样的错误，解压密码123

**Comment by dxyhymn** [comment]
![Uploading image.png…]()

**Comment by zs18347474789** [comment]
没有啊朋友，我解压完能直接用啊，也能下载。没出现这个错误情况。    2020/09/22  12.26

**Comment by wodecs** [comment]
遇到同样的问题

**Comment by quanlook** [comment]
> 初始化下载引擎失败
> ![图片](https://user-images.githubusercontent.com/53852051/93841437-2b653a80-fcc6-11ea-9bd0-cfb74986c122.png)

###  Windows10环境
**[在安全中心 ] 关闭 [病毒和威胁保护] 和 [防火墙和网络保护]**
![Windows检测到危险的dll文件](https://user-images.githubusercontent.com/49576053/93847852-b5b79980-fcda-11ea-8b09-24120eb4f288.png)
![病毒和威胁保护](https://user-images.githubusercontent.com/49576053/93847925-e566a180-fcda-11ea-9565-4f40a38546bb.png)
![防火墙和网络保护](https://user-images.githubusercontent.com/49576053/93847932-eac3ec00-fcda-11ea-9386-587069db273b.png)

**Comment by OneCodeMonkey** [comment]
lbwnb

**Comment by zhumaolin** [comment]
![Uploading image.png…]()

**Comment by lubenweiPD** [comment]
考虑是不是杀软问题，有人已经回答的很详细了。https://github.com/PanDownloadServer/Server/issues/126#issuecomment-696522118
