### ISSUE TITLE
请问有计划发布mac版么

### ISSUE THREAD

**Issue by wqtty** [PanDownloadServer/Server#127]

**Comment by quanlook** [comment]
要说mac版我个人个人觉得发布一个 网页版更香 只要是前后端分离的不管什么平台都可以用
PS：[BaiduPCS-Go](https://github.com/felixonmars/BaiduPCS-Go)

**Comment by lubenweiPD** [comment]
暂时只考虑windows版本，网页版参考内置SVIP的那些。
