### ISSUE TITLE
http请求错误0*6？什么情况有遇到的么？几小时前我还用得好好的。

### ISSUE THREAD

**Issue by zhumaolin** [PanDownloadServer/Server#128]
![image](https://user-images.githubusercontent.com/64005424/93878823-45763b80-fd0d-11ea-95b7-27de6b6fa025.png)

**Comment by zhumaolin** [comment]
![image](https://user-images.githubusercontent.com/64005424/93878823-45763b80-fd0d-11ea-95b7-27de6b6fa025.png)

**Comment by nirolee** [comment]
防火墙

**Comment by lubenweiPD** [comment]
主要考虑是不是Windows的防火墙拦截了访问，可以关闭防火墙后重试。或者访问一次kurukurumi.tk，然后再去打开PD试试。
