### ISSUE TITLE
新版本提示http请求错误 0*6

### ISSUE THREAD

**Issue by Garnuer** [PanDownloadServer/Server#13]

**Comment by lubenweiPD** [comment]
可能是由于aria2c.exe进程被终止，或后台运行着调试器导致，程序带一个反调试检测，针对x64dbg

**Comment by lubenweiPD** [comment]
经过最近的检查，也可能被官网的防火墙所拦截，所以下个版本修复这个问题，因为最近官网的流量有些许异常，疑似被人攻击。
