### ISSUE TITLE
作者您好，我下载无法加速，速度只有几十Kb/s，请问有什么解决方法吗？

### ISSUE THREAD

**Issue by LiHai-26** [PanDownloadServer/Server#131]
我是在github这个链接这儿下载的，解压文件后后，点击运行，下载文件提示下载错误，需要登录，第一次扫码登录未成功，第二次使用账号密码成功登录，但是下载速度最高不到100kb/s，平均只有几十Kb，但我宽带是200M，迅雷下载也有两三M/s的速度，所以肯定不是网络问题，所以想问下，我是需要做什么设置或者再安装什么插件吗？
第一次使用这个软件，不太会用，感谢作者辛苦开发带来的福利，麻烦您空闲时间能够回复下，希望能够尽快用上不受限制的百度网盘，谢谢谢谢

**Comment by sss1243a789** [comment]
实测满速100m/s真的舒服，但是能爽多久呢。。。

**Comment by lubenweiPD** [comment]
伞兵四号通道，128线程。或者伞兵五号云解析，均可满速。

**Comment by LiHai-26** [comment]
> 伞兵四号通道，128线程。或者伞兵五号云解析，均可满速。
您好，请问您是如何选择通道的呢？
我在下载的时候没有看到任何通道选择的地方，想麻烦您告知下，谢谢谢谢
