### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by xlqm2015** [PanDownloadServer/Server#133]
登录账号显示获取bdstoken失败

![$BQ8CQK_ZW9Z BX`4RZSVO5](https://user-images.githubusercontent.com/50951021/93965680-4fdc1800-fd95-11ea-9844-51aa441f0200.png)

**Comment by freesia-fy** [comment]
+1我也是，已经关闭防火墙

**Comment by sss1243a789** [comment]
webkit

**Comment by xlqm2015** [comment]
> Webkit
已经下了webkit 还是一样
![image](https://user-images.githubusercontent.com/50951021/93991596-10c2bc80-fdbf-11ea-867b-a82c361057e8.png)
![image](https://user-images.githubusercontent.com/50951021/93991623-17513400-fdbf-11ea-9bf0-0ba657cbee6e.png)

**Comment by lubenweiPD** [comment]
已修复。请尝试3.5.3版本。
