### ISSUE TITLE
3.5.2，无明显加速效果

### ISSUE THREAD

**Issue by Capricornsong** [PanDownloadServer/Server#134]
相比起百度云客户端，下载速度无明显差异，只有120kb左右。

**Comment by LiHai-26** [comment]
我也是这个问题，而且似乎速度更慢了，用百度网盘还有一百多kb的速度，用这个只有二三十kb的速度

**Comment by zhekantian** [comment]
What's the password of the PanDownloadLBW3.5.2.rar? Help please.

**Comment by sss1243a789** [comment]
> What's the password of the PanDownloadLBW3.5.2.rar? Help please.
try 123

**Comment by sss1243a789** [comment]
惊人的1024线程下载，多大的带宽都给跑满用的人多了百度高管得原地爆炸额

**Comment by Capricornsong** [comment]
> What's the password of the PanDownloadLBW3.5.2.rar? Help please.

No password

**Comment by Capricornsong** [comment]
> What's the password of the PanDownloadLBW3.5.2.rar? Help please.

No password
