### ISSUE TITLE
What's the password of the PanDownloadLBW3.5.2.rar?

### ISSUE THREAD

**Issue by zhekantian** [PanDownloadServer/Server#135]
What's the password of the PanDownloadLBW3.5.2.rar? Help please.
![image](https://user-images.githubusercontent.com/42829479/93987130-c3901c00-fdb9-11ea-81b4-c512cd50e881.png)

**Comment by sss1243a789** [comment]
官网不是写着呢嘛 你用的中文为啥要说英语

**Comment by dis-xcl** [comment]
one two three

**Comment by lubenweiPD** [comment]
The new version has cancelled the password。
