### ISSUE TITLE
账号登录失败，获取bdstoken失败

### ISSUE THREAD

**Issue by Richard0519** [PanDownloadServer/Server#136]
勾选公用网络，扫码登录和cookie登录都试过了...

**Comment by sss1243a789** [comment]
下载webkit啊官网都说明了，直接点下载重启软件就能登陆了 原版软件也是这样

**Comment by Richard0519** [comment]
> 下载webkit啊官网都说明了，直接点下载重启软件就能登陆了 原版软件也是这样

可以请教下，官网说的“webkit核心，node.dll使用PCS通道下载，或者去github下载也行”是怎样操作么，我不太懂...

**Comment by RonaldinhoL** [comment]
一样的问题，3.5.2 已经下载了 node.dll 了

**Comment by AnthonyZhai** [comment]
我遇到了一样的问题：
1）版本：3.5.2，下载了node.dll
2）使用内置浏览器登录失败
3）使用cookie登录失败（参照pandownload官网，编辑成BDUSS=xxx; STOKEN=xxx的形式）
4）都提示“账号登录失败，获取bdstoken失败”

**Comment by weiyx16** [comment]
> 一样的问题，3.5.2 已经下载了 node.dll 了

我这边下载node.dll放到与pandownload.exe同一级，不使用IE内核登录就可以了...

**Comment by weiyx16** [comment]
> > 下载webkit啊官网都说明了，直接点下载重启软件就能登陆了 原版软件也是这样
> 
> 可以请教下，官网说的“webkit核心，node.dll使用PCS通道下载，或者去github下载也行”是怎样操作么，我不太懂...

直接在官网给的这个链接下载node.dll放到对应位置。
![image](https://user-images.githubusercontent.com/29686453/94016497-c3efdd80-fde0-11ea-926f-ad45f7002031.png)

**Comment by RonaldinhoL** [comment]
> > 一样的问题，3.5.2 已经下载了 node.dll 了
> 
> 我这边下载node.dll放到与pandownload.exe同一级，不使用IE内核登录就可以了...

怎么不使用IE内核，没有切换的地方呢？感觉应该还是BUG的原因

**Comment by lubenweiPD** [comment]
新版本已经修复，请尝试3.5.3版本。
