### ISSUE TITLE
 3.5.2，无明显加速效果

### ISSUE THREAD

**Issue by Capricornsong** [PanDownloadServer/Server#137]
相比起百度云客户端，下载速度无明显差异，只有120kb左右

**Comment by Capricornsong** [comment]
https://kinhdown.kinh.cc/
这个亲测有用，可以试试。

**Comment by weiyx16** [comment]
可能在设置里把最大链接改大有好处？我这边能到4mb

**Comment by lubenweiPD** [comment]
请尝试伞兵五号云解析，其与kinhdown的云解析是同一个。
