### ISSUE TITLE
应用无法在电脑上运行

### ISSUE THREAD

**Issue by dilemma-wang** [PanDownloadServer/Server#19]

**Comment by itlubber** [comment]
![image](https://user-images.githubusercontent.com/39397838/92297835-dca16c00-ef75-11ea-9612-ef26ba44e6b6.png)

**Comment by lubenweiPD** [comment]
检查您的hosts文件，删除PanDownload.com相关条目，亦或者点击备用启动。如果还是不行，请关闭后台的调试器。
