### ISSUE TITLE
在安装webkit核心后再打开出现“http请求错误 0x6”，求解

### ISSUE THREAD

**Issue by Antonyrebel** [PanDownloadServer/Server#21]
我先用PCS端口下载了webkit核心，然后重启出现“http请求错误 0x6”，然后我删掉重装再打开还是如此

**Comment by Antonyrebel** [comment]
我还有一个备用的pandownload可以正常使用，对比了一下，发现一个大问题：
请恢复fixpandownload软件的下载和更新，同时从pandownload处移除webkit核心的下载。webkit核心是导致出现错误的罪魁祸首，可能百毒在那个上动了手脚。

**Comment by lubenweiPD** [comment]
那个应该是可以正常使用的，考虑是hosts里有pandownload.com或者是后台有调试器一类的，亦或者被服务器防火墙拦截了？

**Comment by Antonyrebel** [comment]
有什么具体的解决方案吗？

**Comment by Antonyrebel** [comment]
啊，我调了一下防火墙，然后可以正常运作了，但是下载时又出现“but a control file (*aria2) does not exist. Download was canceled in order to prevent...”我再弄一下吧

**Comment by Antonyrebel** [comment]
关掉了防火墙，可以正常打开，但是只成功了一次。然后成功那次在下载时说缺乏控制文件（*aria2）下载失败了，然后关掉重启就又GG了。
有没有什么具体的方案？我手里有一个可以正常使用的可以给你发过来

**Comment by lubenweiPD** [comment]
> 关掉了防火墙，可以正常打开，但是只成功了一次。然后成功那次在下载时说缺乏控制文件（*aria2）下载失败了，然后关掉重启就又GG了。
> 有没有什么具体的方案？我手里有一个可以正常使用的可以给你发过来

重新解压一份，然后把node.dll复制过去康康？具体的方案暂时没有。感觉你这个是多种原因造成的

**Comment by tommycai8** [comment]
没有node.dll，同样报错，请问如何排查

**Comment by Antonyrebel** [comment]
我把防火墙里所有的aria2文件都删掉，再次解压打开时防火墙予以通过，现在没有node.dll可以用。看看以后还会有什么问题吧

**Comment by nirolee** [comment]
同样报错

**Comment by nirolee** [comment]
让防火墙予以通过，就可以解决这个问题
