### ISSUE TITLE
HTTP请求错误 0X6

### ISSUE THREAD

**Issue by lixingqiancs** [PanDownloadServer/Server#215]
![image](https://user-images.githubusercontent.com/44748328/96663649-a5e7af80-1383-11eb-91f6-8e26dcdf3c29.png)

**Comment by weihang-wills** [comment]
关掉windows的防火墙，在安全中心里面把它设为允许就可以了。这是被安全中心拦截了。

**Comment by xfFelix** [comment]
关闭window10 病毒扫描就行
![1](https://user-images.githubusercontent.com/39913750/96840776-7d43e080-147d-11eb-822a-2d3cded6a8b4.png)
![2](https://user-images.githubusercontent.com/39913750/96840781-7f0da400-147d-11eb-94fc-8ae309677955.png)

**Comment by hxbmlfj** [comment]
对，关掉win10的病毒和威胁防护功能 就ok了！  不会的点击这里：https://zhidao.baidu.com/question/269414238179928365.html
