### ISSUE TITLE
接收数据失败（1）

### ISSUE THREAD

**Issue by M56SG** [PanDownloadServer/Server#22]
按照教程下载后使用pandownload.exe，然后就提示接收数据失败（1），无论试几次都一样。用管理员身份打开备用启动方式后提示找不到“PanData\aria2c.exe"。确认aria2c.exe在PanData里，没有被杀软删掉。这个要怎么解决。
![1](https://user-images.githubusercontent.com/51167244/92328960-eb337480-f096-11ea-8b50-90bffb8d2006.png)
![2](https://user-images.githubusercontent.com/51167244/92328963-ecfd3800-f096-11ea-9b58-b4a7b7104cc7.png)
![3](https://user-images.githubusercontent.com/51167244/92328964-eec6fb80-f096-11ea-84a3-84c1191610a5.png)
![4](https://user-images.githubusercontent.com/51167244/92328966-ef5f9200-f096-11ea-9de8-5bf1793a9b6b.png)

**Comment by lubenweiPD** [comment]
服务器问题，很大可能被服务器防火墙拦截了。下个版本修复，目前可以试试手动访问一下kurukurumi.tk，然后再去启动软件。
