### ISSUE TITLE
https://github.com/semver/semver/issues/611#issue-694637499

### ISSUE THREAD

**Issue by 93iamghost** [PanDownloadServer/Server#24]
https://github.com/semver/semver/issues/611#issue-694637499Host *
  AddKeysToAgent yes
  UseKeychain yes
  IdentityFile ~/.ssh/id_rsahttps://github.com/cli/cli/issues/1624#issue-693315689

**Comment by lubenweiPD** [comment]
![image](https://user-images.githubusercontent.com/70097750/92491676-1350de00-f225-11ea-9926-30717a496782.png)
