### ISSUE TITLE
一直程序环境异常

### ISSUE THREAD

**Issue by CryFun** [PanDownloadServer/Server#3]
多次运行，管理员运行，依旧如此
![20200823095112](https://user-images.githubusercontent.com/62494001/90969046-5709cf00-e526-11ea-8521-d6fe2987c970.png)

**Comment by VV-Danny** [comment]
我这边也是报同样的错误，win8.1原版操作系统，64位，软件一般都只用免安装版，没有改过什么系统文件

**Comment by muququmu** [comment]
俺也一样！lbw快想想办法！
win8.1原版操作系统，64位，软件一般都只用免安装版

**Comment by CryFun** [comment]
> 是什么系统呢？修改过系统文件么？

没有，win7x64

**Comment by CryFun** [comment]
发件人: lubenwei-PD <notifications@github.com> 
发送时间: 2020年8月23日 星期日 20:07
收件人: PanDownloadServer/Server <Server@noreply.github.com>
抄送: CryFun <q1526899190@gmail.com>; Author <author@noreply.github.com>
主题: Re: [PanDownloadServer/Server] 一直程序环境异常 (#3)

 

是什么系统呢？修改过系统文件么？

 

Win7x64，未修改文件

**Comment by lubenweiPD** [comment]
3.4版本试着改善这个问题，这问题是因为程序的反调试检测，前几天观察到了一处会触发的地方。。我会在3.4版本优化
