### ISSUE TITLE
请更新Aria2c,官网: https://kurukurumi.tk

### ISSUE THREAD

**Issue by tongle1** [PanDownloadServer/Server#31]
下载解压后运行PanDownload，会初始化失败，然后弹窗 请更新Aria2c,官网: https://kurukurumi.tk，操作系统版本为windows7
![image](https://user-images.githubusercontent.com/28292983/92446295-327d4a80-f1e8-11ea-88af-579868e7c78c.png)

**Comment by lubenweiPD** [comment]
下载3.4版本试试，如果还提示这个，试着访问一下官网后打开pd。
