### ISSUE TITLE
啥原理方便讲下吗，纯好奇

### ISSUE THREAD

**Issue by jishuo1213** [PanDownloadServer/Server#34]

**Comment by lubenweiPD** [comment]
通过补丁重定向pandownload的请求到本地服务器，以此恢复部分功能，通过自写下载脚本和魔改部分DLL实现对接新的下载通道，当然，下载部分加密，防止别有用心的人拿来。。

**Comment by yansheng836** [comment]
> 通过补丁重定向pandownload的请求到本地服务器，以此恢复部分功能，通过自写下载脚本和魔改部分DLL实现对接新的下载通道，当然，下载部分加密，防止别有用心的人拿来。。

@lubenweiPD （来自粉丝的关心:thinking:）这是否侵权？是否会触碰xx的利益？毕竟有前车之签，是否有必要添加个免责声明或者license？
