### ISSUE TITLE
所有的方式登录失败，获取bdstoken失败

### ISSUE THREAD

**Issue by Summary-wcj** [PanDownloadServer/Server#39]
登录失败，获取bdstoken失败，大佬这个怎么处理

**Comment by yansheng836** [comment]
第一次登陆出现该问题，再次登录就可以了……

**Comment by Summary-wcj** [comment]
我重新登录好几遍了，都是一样 不知道是什么原因，账号密码、扫描、cookie都试了好几遍

**Comment by Shinku1014** [comment]
我也是一样的情况

**Comment by Leo4ML** [comment]
同样情况+1

**Comment by Davidlasky** [comment]
+1

**Comment by juxiaoz1** [comment]
把node.dll删掉，重新打开软件，接着点击登陆 有个温馨提示 ，不管他 ，然后点击登录 用二维码登陆就搞定

**Comment by lubenweiPD** [comment]
下个版本修复。目前在测试BUG，可以按https://github.com/PanDownloadServer/Server/issues/39#issuecomment-690368785
的试试
