### ISSUE TITLE
启动失败

### ISSUE THREAD

**Issue by MLC1158** [PanDownloadServer/Server#4]
提示启动失败，已经下载了node.dll，用管理员身份打开也不行，TG联系不上
![image](https://user-images.githubusercontent.com/60974273/90973580-da8ee480-e555-11ea-98bf-d9043943d0a8.png)

**Comment by lubenweiPD** [comment]
> 都试过了，还是提示“初始化下载引擎错误”

首先检查aria2c.exe文件是否存在，其次查看提示错误的时候，aria2c.exe和aria2cp.exe进程是否存在。

**Comment by MLC1158** [comment]
aria2c.exe文件不存在，从三个下载链接下载的压缩包中均未找到该文件
提示错误的时候，aria2c.exe进程存在，aria2cp.exe进程不存在

**Comment by Garnuer** [comment]
下载下来的好像没有aria2c.exe这个文件。无法正常使用。初始化下载引擎错误

**Comment by Lantrancy** [comment]
这个aria2c被Windowsdefender杀了

**Comment by MLC1158** [comment]
> 这个aria2c被Windowsdefender杀了

我用了火绒

**Comment by Lantrancy** [comment]
> > 这个aria2c被Windowsdefender杀了
> 
> 我用了火绒

反正这个aria2c貌似只是个劫持接口，后台又下载了一个aria2cp和PYG.DLL，三个全都被杀，不知道安全不安全

**Comment by MLC1158** [comment]
> > > 这个aria2c被Windowsdefender杀了
> > 
> > 
> > 我用了火绒
> 
> 反正这个aria2c貌似只是个劫持接口，后台又下载了一个aria2cp和PYG.DLL，三个全都被杀，不知道安全不安全

我用别的含有aria2c的软件就可以，能教我怎么下载吗？

**Comment by Lantrancy** [comment]
> > > > 这个aria2c被Windowsdefender杀了
> > > 
> > > 
> > > 我用了火绒
> > 
> > 
> > 反正这个aria2c貌似只是个劫持接口，后台又下载了一个aria2cp和PYG.DLL，三个全都被杀，不知道安全不安全
> 
> 我用别的含有aria2c的软件就可以，能教我怎么下载吗？

不是，这个aria2c是个修改的版本，真正的aria2c是个命令行下载工具，修改的版本后台又下来两个dll和一个aria2cp（这个是下载工具），然后全被杀了，反正我需要下载就允许了，不放心可以放到虚拟机

**Comment by Lantrancy** [comment]
> > > > > 这个aria2c被Windowsdefender杀了
> > > > 
> > > > 
> > > > 我用了火绒
> > > 
> > > 
> > > 反正这个aria2c貌似只是个劫持接口，后台又下载了一个aria2cp和PYG.DLL，三个全都被杀，不知道安全不安全
> > 
> > 
> > 我用别的含有aria2c的软件就可以，能教我怎么下载吗？
> 
> 不是，这个aria2c是个修改的版本，真正的aria2c是个命令行下载工具，修改的版本后台又下来两个dll和一个aria2cp（这个是下载工具），这个可能触发了行为保护然后全被杀了，反正我需要下载就允许了，不放心可以放到虚拟机

**Comment by MLC1158** [comment]
> > > > > > 这个aria2c被Windowsdefender杀了
> > > > > 
> > > > > 
> > > > > 我用了火绒
> > > > 
> > > > 
> > > > 反正这个aria2c貌似只是个劫持接口，后台又下载了一个aria2cp和PYG.DLL，三个全都被杀，不知道安全不安全
> > > 
> > > 
> > > 我用别的含有aria2c的软件就可以，能教我怎么下载吗？
> 
> 不是，这个aria2c是个修改的版本，真正的aria2c是个命令行下载工具，修改的版本后台又向下两个dll和一个aria2cp（这个是下载工具），这个可能触发了行为保护然后全被杀了，反正我需要下载就允许了，不放心可以放到虚拟机

我在压缩包里就可以打开，但解压了就打开不了了

**Comment by lubenweiPD** [comment]
> > > > > > 这个aria2c被Windowsdefender杀了
> > > > > 
> > > > > 
> > > > > 我用了火绒
> > > > 
> > > > 
> > > > 反正这个aria2c貌似只是个劫持接口，后台又下载了一个aria2cp和PYG.DLL，三个全都被杀，不知道安全不安全
> > > 
> > > 
> > > 我用别的含有aria2c的软件就可以，能教我怎么下载吗？
> 
> 不是，这个aria2c是个修改的版本，真正的aria2c是个命令行下载工具，修改的版本后台又下来两个dll和一个aria2cp（这个是下载工具），这个可能触发了行为保护然后全被杀了，反正我需要下载就允许了，不放心可以放到虚拟机

想法没错,aria2c.exe是负责加载劫持模块的，后台有两个PYG.DLL，一个负责劫持Pandownload.exe，一个负责劫持aria2cp.exe，负责Pandownload.exe的是我写的，负责aria2cp.exe的是别人的，报毒的主要原因考虑是壳的问题。不过实际上是后台释放这些DLL。

**Comment by lubenweiPD** [comment]
考虑是不是杀软干掉了，然后康康有没有VC2017的运行库

**Comment by lubenweiPD** [comment]
新版本已经更新，本问题关闭
