### ISSUE TITLE
无法启动，初始化下载引擎失败

### ISSUE THREAD

**Issue by johntitor1040** [PanDownloadServer/Server#5]
昨天还能用的，深夜进行中的下载先是报错停止（错误忘了，限速下载挂到一定时候就会中断的），然后尝试切换账号时登陆失败，报http错误0x4（cookie登录也是），退出重启就无法启动应用了，报初始化下载引擎失败。谢谢。

**Comment by lubenweiPD** [comment]
考虑是不是杀软动的手qwq

**Comment by lavy233** [comment]
我今天刚下的，打开跟楼上同样的提示

**Comment by johntitor1040** [comment]
我的问题解决了，删掉文件夹重新解压了一遍，这次windows安全中心没有动作

**Comment by lubenweiPD** [comment]
新版本已经更新，本问题关闭
