### ISSUE TITLE
程序启动失败

### ISSUE THREAD

**Issue by axh2008** [PanDownloadServer/Server#54]
程序环境异常

**Comment by lubenweiPD** [comment]
留下系统版本，系统是ghost安装的吗？

**Comment by axh2008** [comment]
win7 pack1  是ghost安装的

**Comment by lubenweiPD** [comment]
> win7 pack1 是ghost安装的

检查系统文件的数字签名，文件有可能不是微软官网的签名，有可能被ghost发布者内置了什么奇奇怪怪的东西。
