### ISSUE TITLE
没登陆不让下载，但是登录又失败，无解

### ISSUE THREAD

**Issue by dingguotu** [PanDownloadServer/Server#56]
![image](https://user-images.githubusercontent.com/17001225/92839806-f417a380-f412-11ea-92a1-5bab29ff38ef.png)

![image](https://user-images.githubusercontent.com/17001225/92839739-e3672d80-f412-11ea-9527-16ef40526892.png)

**Comment by zgw-1998** [comment]
我也是这样，有没有大佬，求解

**Comment by lubenweiPD** [comment]
用伞兵系列通道，pcs和默认大部分情况下是摆设。

**Comment by dingguotu** [comment]
别关这么早啊，我都选不了伞兵通道，怎么玩
![image](https://user-images.githubusercontent.com/17001225/93033113-6680c180-f667-11ea-8b41-440ba3f0a58e.png)
