### ISSUE TITLE
账号登录失败

### ISSUE THREAD

**Issue by GNOS233** [PanDownloadServer/Server#58]
正常登录或者cookie登录都显示【获取bdstoken失败】

**Comment by WandererinHub** [comment]
兄弟你可能要看一下杀毒软件有没有拦截，然后去启动PanData里的aria2c,我本来也登陆不了，现在行了，希望能帮到你

**Comment by GNOS233** [comment]
> 兄弟你可能要看一下杀毒软件有没有拦截，然后去启动PanData里的aria2c，我本来也登陆不了，现在行了，希望能帮到你

感谢！关闭杀软后成功登陆

**Comment by WandererinHub** [comment]
> > 兄弟你可能要看一下杀毒软件有没有拦截，然后去启动PanData里的aria2c，我本来也登陆不了，现在行了，希望能帮到你
> 
> 感谢！关闭杀软后成功登陆

那就好，我也搞得挺久的了，弄完来帮下忙

**Comment by lubenweiPD** [comment]
嗯，杀软着实麻烦。
