### ISSUE TITLE
作者引用本人的补丁这件事。。希望看一下

### ISSUE THREAD

**Issue by 1582421598** [PanDownloadServer/Server#6]
哇，真的，我视频6月份发的，然后被删了，这几天有人私聊问我PD的问题，我才知道有这个版本，然后今天发现了这个
![eabd391ee6b913219c64f0311d186250e29c3523](https://user-images.githubusercontent.com/26507452/91467013-8b80e080-e8c2-11ea-8342-dd86b18d400f.png)
最迷的，我电脑上当时根本不显示这个，后来发现是作者的补丁覆盖了我的。。
作者大大啊，你要真用。。说一声啊，我直接把数据给你就行，你和我用的都是一个工具，然后你这样搞。。我有点背锅啊???

**Comment by VectorZhao** [comment]
你就是B站：上学困难户   本尊？

**Comment by 1582421598** [comment]
额，没人吗。。我得去B站投专栏了

**Comment by johntitor1040** [comment]
喔，也是，小心百度资本家找茬啊，的确要很注意才行

**Comment by 1582421598** [comment]
> 喔，也是，小心百度资本家找茬啊，的确要很注意才行

主要是他这样搞。。都以为我是作者了，感觉成了背锅侠。。

**Comment by lubenweiPD** [comment]
并没有覆盖的意思，只是没来得及通知，官网已经更新程序各个组件的来源
