### ISSUE TITLE
程序异常

### ISSUE THREAD

**Issue by SIMElsmao** [PanDownloadServer/Server#60]
打开的时候出现程序异
![捕获](https://user-images.githubusercontent.com/35984381/92853979-0c8fba00-f423-11ea-89a5-64aad5b4f212.PNG)
常

**Comment by lubenweiPD** [comment]
什么版本的系统啊？是ghost吗？

**Comment by SIMElsmao** [comment]
不是ghost ，win8.1系统

**Comment by lubenweiPD** [comment]
尝试新版，然后安装VC2017运行库看看。
