### ISSUE TITLE
选不了伞兵通道

### ISSUE THREAD

**Issue by aniop** [PanDownloadServer/Server#61]
选不了伞兵通道， 通道只有默认和PCS接口，是3.4版本去除了吗

**Comment by WandererinHub** [comment]
这两个中间应该有几行空格，我这里是这样

**Comment by aniop** [comment]
![image](https://user-images.githubusercontent.com/43027069/92887221-e67c1100-f446-11ea-97b8-a706d0c73e9b.png)
我这边是这样就只有两个

**Comment by WandererinHub** [comment]
> ![image](https://user-images.githubusercontent.com/43027069/92887221-e67c1100-f446-11ea-97b8-a706d0c73e9b.png)
> 我这边是这样就只有两个

我也是3.4版本，你是不是漏了点文件没下载

**Comment by aniop** [comment]
> > ![image](https://user-images.githubusercontent.com/43027069/92887221-e67c1100-f446-11ea-97b8-a706d0c73e9b.png)
> > 我这边是这样就只有两个
> 
> 我也是3.4版本，你是不是漏了点文件没下载

一个主程序压包，node.dll文件，请问还需要下载那些文件

**Comment by WandererinHub** [comment]
> > > ![image](https://user-images.githubusercontent.com/43027069/92887221-e67c1100-f446-11ea-97b8-a706d0c73e9b.png)
> > > 我这边是这样就只有两个
> > 
> > 
> > 我也是3.4版本，你是不是漏了点文件没下载
> 
> 一个主程序压包，node.dll文件，请问还需要下载那些文件

应该就这些，node要跟pandownload.exe放在同一个目录页

**Comment by aniop** [comment]
> > > > ![image](https://user-images.githubusercontent.com/43027069/92887221-e67c1100-f446-11ea-97b8-a706d0c73e9b.png)
> > > > 我这边是这样就只有两个
> > > 
> > > 
> > > 我也是3.4版本，你是不是漏了点文件没下载
> > 
> > 
> > 一个主程序压包，node.dll文件，请问还需要下载那些文件
> 
> 应该就这些，node要跟pandownload.exe放在同一个目录页

对的，那应该是没有漏下载，倒是奇怪

**Comment by WandererinHub** [comment]
> > > > > ![image](https://user-images.githubusercontent.com/43027069/92887221-e67c1100-f446-11ea-97b8-a706d0c73e9b.png)
> > > > > 我这边是这样就只有两个
> > > > 
> > > > 
> > > > 我也是3.4版本，你是不是漏了点文件没下载
> > > 
> > > 
> > > 一个主程序压包，node.dll文件，请问还需要下载那些文件
> > 
> > 
> > 应该就这些，node要跟pandownload.exe放在同一个目录页
> 
> 对的，那应该是没有漏下载，倒是奇怪

或者你把杀毒软件关一下重新下载

**Comment by lubenweiPD** [comment]
emmmmm，如果账号能登陆但是没有通道。试试备用启动？或者把pandata的temp目录删了看看会不会重新创建。

**Comment by FrankXiong1985** [comment]
> emmmmm，如果账号能登陆但是没有通道。试试备用启动？或者把pandata的temp目录删了看看会不会重新创建。

一样的问题，temp里面有script的缓存但是似乎无法正常解密（或者说生成lua脚本), 并且log报错，附上：

2020-09-11 01:03:45 [WARN] lua error: error loading module 'socket' from file './PanData/script/lib/socket.dll':
	找不到指定的模块。
2020-09-11 01:03:45 [WARN] lua error: error loading module 'socket' from file './PanData/script/lib/socket.dll':
	找不到指定的模块。
2020-09-11 01:03:45 [WARN] lua error: error loading module 'socket' from file './PanData/script/lib/socket.dll':
	找不到指定的模块。
2020-09-11 01:03:45 [WARN] lua error: error loading module 'socket' from file './PanData/script/lib/socket.dll':
	找不到指定的模块。

temp也清空过，并且确实会提示正在更新脚本，然后还是一样的。

**Comment by austress99** [comment]
Yes I am going

**Comment by FrankXiong1985** [comment]
> > > > > > ![image](https://user-images.githubusercontent.com/43027069/92887221-e67c1100-f446-11ea-97b8-a706d0c73e9b.png)
> > > > > > 我这边是这样就只有两个
> > > > > 
> > > > > 
> > > > > 我也是3.4版本，你是不是漏了点文件没下载
> > > > 
> > > > 
> > > > 一个主程序压包，node.dll文件，请问还需要下载那些文件
> > > 
> > > 
> > > 应该就这些，node要跟pandownload.exe放在同一个目录页
> > 
> > 
> > 对的，那应该是没有漏下载，倒是奇怪
> 
> 或者你把杀毒软件关一下重新下载



> emmmmm，如果账号能登陆但是没有通道。试试备用启动？或者把pandata的temp目录删了看看会不会重新创建。

兄弟萌，快谢谢我，找到解决办法:
1. 来这个网站下载 **VS运行时** 合集:https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/
2. 下完了不能看吧，那肯定是安装
3. 猜测: 根据作者以往的回答，应该是VS 2017运行时, 但是我为了保险都装了, 单纯装2017 没测试
4. 仅适用于log 提示错误:
```
_[WARN] lua error: error loading module 'socket' from file './PanData/script/lib/socket.dll':
找不到指定的模块。_
```
的小伙伴。

**Comment by lubenweiPD** [comment]
https://github.com/PanDownloadServer/Server/issues/61#issuecomment-691763671
