### ISSUE TITLE
登录账号失败，http请求错误（0x1c）

### ISSUE THREAD

**Issue by dis-xcl** [PanDownloadServer/Server#66]
Pandownload卢本伟3.4版，账号密码登录、扫码登陆、cookies登陆都用了，都是登录账号失败，http请求错误（0x1c），没法使用。node.dll已经放到了pandownload.exe同目录，确认防火墙已经开放通过，请问怎么解决啊？

**Comment by lubenweiPD** [comment]
aria2c.exe和aria2cp.exe检查是否被杀软误杀，然后看看后台是不是开着x64dbg之类的。
