### ISSUE TITLE
获取bdtoken 失败

### ISSUE THREAD

**Issue by lyj0309** [PanDownloadServer/Server#69]
![image](https://user-images.githubusercontent.com/50474995/92985386-8176f880-f4e4-11ea-8bab-0765f97ec427.png)

**Comment by GuoJuna** [comment]
我也是,找到解决方案吗

**Comment by lubenweiPD** [comment]
试试cookie登陆。

**Comment by dmankill** [comment]
cookie登录也是提示这个

**Comment by yuanhang110** [comment]
我也是，cookie登陆也提示这个

**Comment by Toxiang** [comment]
把windows实时防护关了

**Comment by lubenweiPD** [comment]
已经修复。
