### ISSUE TITLE
Yes I am going

### ISSUE THREAD

**Issue by austress99** [PanDownloadServer/Server#70]
Yes I am going 

_Originally posted by @austress99 in https://github.com/PanDownloadServer/Server/issues/61#issuecomment-691420131_

**Comment by austress99** [comment]
> Yes I am going 
> 
> _Originally posted by @austress99 in https://github.com/PanDownloadServer/Server/issues/61#issuecomment-691420131_

@austress99

**Comment by lubenweiPD** [comment]
尝试新版。
