### ISSUE TITLE
zip password?

### ISSUE THREAD

**Issue by yungongzi** [PanDownloadServer/Server#76]

**Comment by yansheng836** [comment]
If you have questions, please check the issues first.

If you don't know how to ask a question, look at this: <https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way>.

duplicate:https://github.com/PanDownloadServer/Server/issues/67 , https://github.com/PanDownloadServer/Server/issues/38

**Comment by zhenguozhao** [comment]
password： 123

**Comment by lubenweiPD** [comment]
123。
