### ISSUE TITLE
获取bdstoken失败

### ISSUE THREAD

**Issue by yuanhang110** [PanDownloadServer/Server#77]
不能登陆

**Comment by WuDongG** [comment]
获取bdstoken失败，登陆失败~

**Comment by yuantao-yin** [comment]
获取bdstoken失败，登陆失败

**Comment by wz36125** [comment]
不能登录的嘛？

**Comment by Ryan-ss** [comment]
获取bdstoken失败，无法登陆

**Comment by DeepFeeling-1999** [comment]
windows安全那里，会自动检测出危害，然后隔离，你需要手动允许，
![image](https://user-images.githubusercontent.com/44224016/93095367-96ff4480-f6d5-11ea-9bd3-6f082953069a.png)

**Comment by lubenweiPD** [comment]
已经修复。
