### ISSUE TITLE
为什么登录跟不登录都只有两个通道的？

### ISSUE THREAD

**Issue by gimgoo** [PanDownloadServer/Server#78]
根本看不到更新日志所说的什么伞兵通道啊
![image](https://user-images.githubusercontent.com/31849284/93009348-725e7c00-f5b2-11ea-93b7-87bbc03247b8.png)

**Comment by gimgoo** [comment]
去翻了下Issue发现很早有人提出这个问题了，加入了node.dll到exe同目录下也无济于事

**Comment by dingguotu** [comment]
我更惨，登陆失败，通道也只有这两个，下载提示要先登录，这个个人都是懵的

**Comment by FrankXiong1985** [comment]
兄弟萌，快谢谢我，找到解决办法:
1. 来这个网站下载 **VS运行时** 合集:https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/
2. 下完了不能看吧，那肯定是安装
3. 猜测: 根据作者以往的回答，应该是VS 2017运行时, 但是我为了保险都装了, 单纯装2017 没测试
4. 仅适用于log 提示错误:
```
[WARN] lua error: error loading module 'socket' from file './PanData/script/lib/socket.dll':
找不到指定的模块。
```
的小伙伴。

**Comment by lubenweiPD** [comment]
VS2017运行库，然后检查杀软是不是干掉aria2c.exe了。
