### ISSUE TITLE
下载的文件解压失败的情况

### ISSUE THREAD

**Issue by WarriorFromLongAgo** [PanDownloadServer/Server#79]
version 3.4
软件下载时间：20200913
下载文件：一个VMware的镜像
问题经过：下载的时候断断续续，偶尔报错 no aviable，需要重新点击全部开始，下载完成后，提示压缩文件损坏

**Comment by austress99** [comment]
__

**Comment by lubenweiPD** [comment]
PD设置里把文件校验打开？
