### ISSUE TITLE
已解决 只有2个 通道的情况(无伞兵通道)

### ISSUE THREAD

**Issue by FrankXiong1985** [PanDownloadServer/Server#81]
兄弟萌，快谢谢我，找到解决办法:
1. 来这个网站下载 **VS运行时** 合集:https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/
2. 下完了不能看吧，那肯定是安装
3. 猜测: 根据作者以往的回答，应该是VS 2017运行时, 但是我为了保险都装了, 单纯装2017 没测试
4. 仅适用于log 提示错误:
```
[WARN] lua error: error loading module 'socket' from file './PanData/script/lib/socket.dll':
找不到指定的模块。
```
的小伙伴。

**Comment by FrankXiong1985** [comment]
忘了说, 感谢作者的维护！

**Comment by lubenweiPD** [comment]
这个DLL确实，拿VS2017重编译了一份，所以需要相应的运行库。
