### ISSUE TITLE
初始化下载引擎失败

### ISSUE THREAD

**Issue by GinaLai** [PanDownloadServer/Server#82]
我平常有三台电脑在使用，其它两台都能成功登陆，但还有一台打开程序后会加载很久后提示“初始化下载引擎失败”，无论开多少次都一样，管理员打开的方式和备用启动方法也都全试过了，也按照pandownload官网的方法关了防火墙和修改port，还是这样子。。。到底是什么因素影响呢？请大大指教。（主要是我打不开程序的那台电脑，偏偏是我专门拿来下载东西到本地的，想用回之前能打开的3.3版呢，就被更新的窗口挡住了。。。。哭~~）

**Comment by lubenweiPD** [comment]
看看vs2017运行库安装了吗，然后看看是不是杀软把新版的程序干掉了，如aria2c.exe和aria2cp.exe。

**Comment by shua1ng** [comment]
请问一下aria2c启动初始化失败，KinhDown稳定版   版本1.0.88不兼容，小白钢珠额账号，不太会，请指教

**Comment by lubenweiPD** [comment]
如果还遇到，截图发出来。

**Comment by shua1ng** [comment]
还有什么需要提供的，直接邮件沟通吗？发送自我的三星盖乐世智能手机。
-------- 原始信息 --------发件人： lubenweiPD <notifications@github.com> 日期: 2020/9/20  09:26  (GMT+08:00) 收件人： PanDownloadServer/Server <Server@noreply.github.com> 抄送： shua1ng <YS19970612@163.COM>, Comment <comment@noreply.github.com> 主题： Re: [PanDownloadServer/Server] 初始化下载引擎失败 (#82) 

如果还遇到，截图发出来。
