### ISSUE TITLE
解压压缩包，查看里面的版本还是2.2.2，登录出现bdstoken失败

### ISSUE THREAD

**Issue by lxlhz** [PanDownloadServer/Server#84]

**Comment by DeepFeeling-1999** [comment]
windows安全那里，会自动检测出危害，然后隔离，你需要手动允许，
![image](https://user-images.githubusercontent.com/44224016/93095288-7d5dfd00-f6d5-11ea-9f40-8176310d909a.png)

**Comment by lubenweiPD** [comment]
是的，你需要保证aria2c.exe和aria2cp.exe不被杀软干掉。

**Comment by akudamatata** [comment]
> 是的，你需要保证aria2c.exe和aria2cp.exe不被杀软干掉。

确实没被干掉 依然登录不上去 用cookies也不行

**Comment by lubenweiPD** [comment]
> > 是的，你需要保证aria2c.exe和aria2cp.exe不被杀软干掉。
> 
> 确实没被干掉 依然登录不上去 用cookies也不行

熊厂更改了API的数据返回。需要修复一下。

**Comment by lxlhz** [comment]
> > > 是的，你需要保证aria2c.exe和aria2cp.exe不被杀软干掉。
> > 
> > 
> > 确实没被干掉 依然登录不上去 用cookies也不行
> 
> 熊厂更改了API的数据返回。需要修复一下。

好的，我这边版本还是显示2.2.2呢

**Comment by lubenweiPD** [comment]
已经修复。
