### ISSUE TITLE
bdstoken在登陆的时候获取失败

### ISSUE THREAD

**Issue by dzc217** [PanDownloadServer/Server#89]
bdstoken依旧无法获取

**Comment by AlieZ-Deng** [comment]
同样是登录不上，请问如何解决

**Comment by AlieZ-Deng** [comment]
把那个windows自带杀毒关闭了，还是无法获取

**Comment by akudamatata** [comment]
我也一样 无法获取

**Comment by luhua98989898** [comment]
怎么登陆不了？

**Comment by mingmengyuan** [comment]
登陆不了

**Comment by lubenweiPD** [comment]
根据分析得知，百度疑似更改了数据格式，导致软件数据处理的时候出现了问题，晚点修复。

**Comment by gululujun** [comment]
> 根据分析得知，百度疑似更改了数据格式，导致软件数据处理的时候出现了问题，晚点修复。

能不能用另说，你们做这个，会不会又找借口对你们不利？

**Comment by AlieZ-Deng** [comment]
> > 根据分析得知，百度疑似更改了数据格式，导致软件数据处理的时候出现了问题，晚点修复。
> 
> 能不能用另说，你们做这个，会不会又找借口对你们不利？

是的，怕是对开发者不利

**Comment by Gitelement** [comment]
> > > 根据分析得知，百度疑似更改了数据格式，导致软件数据处理的时候出现了问题，晚点修复。
> > 
> > 
> > 能不能用另说，你们做这个，会不会又找借口对你们不利？
> 
> 是的，怕是对开发者不利

俺也一样。

**Comment by pcdd21** [comment]
是不是百度又封了，我的登录登陆提示账号登陆失败，获取bdstoken失败！百度真是的，自己不为广大用户发福利，还限制别人，我们很支持开发者，但如果度娘态度强硬的话还是希望你。。。毕竟胳膊拗不过大腿，在此感谢广大开发者

**Comment by oceanus1992** [comment]
百度回头已经把我账号限速了，是真的恶心，希望作者能早日解决问题吧

**Comment by lifan5550** [comment]
百度真是lj,

**Comment by hust-suwb** [comment]
+1。原来不是我个人的问题。

**Comment by lubenweiPD** [comment]
已修复。
