### ISSUE TITLE
解压需要密码，如何获取？

### ISSUE THREAD

**Issue by wanghaiming012** [PanDownloadServer/Server#93]
![1600149251(1)](https://user-images.githubusercontent.com/22538308/93171075-ff443980-f75a-11ea-84ff-089567c14db7.jpg)

**Comment by JaSmileYo** [comment]
同问，卢本伟牛逼

**Comment by lightChaserX** [comment]
123

**Comment by lifan5550** [comment]
还真就是123

**Comment by yansheng836** [comment]
@wanghaiming012 你们提issue都不先搜issue

link: <https://github.com/PanDownloadServer/Server/issues?q=密码>

**Comment by deepinAcademy** [comment]
密码是：123
