### ISSUE TITLE
昨天还好好的，今天好像用不了啦，有谁知道什么情况么

### ISSUE THREAD

**Issue by zhumaolin** [PanDownloadServer/Server#96]
账号登录失败，获取bdstoken失败，获取BDUSS和STOKEN后用cookie也登录不了

**Comment by zhumaolin** [comment]
账号登录失败，获取bdstoken失败，获取BDUSS和STOKEN后用cookie也登录不了

**Comment by xuxinqiujiaoyizhiyang** [comment]
我也想问怎么解决登录时候出现的这个问题

**Comment by zhumaolin** [comment]
哈哈，我也木有找到方法

**Comment by erlkingrui007** [comment]
第一次用 也提示获取失败- -

**Comment by a2746374493** [comment]
账号登录失败，获取bdstoken失败 。。。昨天还能用来着

**Comment by zhanyongsheng** [comment]
bdstoken失败

**Comment by Tmcity** [comment]
bdstoken失败+1

**Comment by ldm0316** [comment]
失败+1

**Comment by yansheng836** [comment]
https://github.com/PanDownloadServer/Server/blob/master/README.md

**Comment by pcdd21** [comment]
百度哎，真是没法说百度，太恶心人了

**Comment by lubenweiPD** [comment]
已修复。
