### ISSUE TITLE
界面皮肤太亮了，亮瞎了我的眼，内容都看不到，谢谢

### ISSUE THREAD

**Issue by ZHOUKAI1** [PanDownloadServer/Server#99]
界面皮肤太亮了，亮瞎了我的眼，内容都看不到，谢谢

**Comment by MrLizs** [comment]
> 界面皮肤太亮了，亮瞎了我的眼，内容都看不到，谢谢

有个衣服样式的按钮，可以改

**Comment by lubenweiPD** [comment]
https://github.com/PanDownloadServer/Server/issues/99#issuecomment-693231954
